### ISSUE TITLE
Evil Buyer has x3 financial damage multiplier after receiving goods

### ISSUE THREAD

**Issue by SmallAndSoft** [AlejandroDiaz666/mad-stores#1]
If buyer opts to burn escrow he looses 150%-100%=50% of price (because he has a good that he payed 150% for) while seller looses both the good and 50% bond equaling in 150% loss.

**Comment by AlejandroDiaz666** [comment]
This is as-designed. The buyer deposits the payment price of the item, plus a 50% bond. If it all goes to h-ll, then the buyer loses the payment price and his bond -- but we really have no way of knowing if the product was actually delivered -- so while an honest buyer could lose 150% of the purchase price, a dishonest buyer would have received the item in exchange for the purchase price, and the extra amount forfeit would be the only the 50% bond; Similarly the seller deposits a 50% bond, but is presumably also going to part with the item, which is worth the purchase price. So while an honest seller could lose 150% of the purchase price (the item and the bond), a dishonest seller would only forfeit the 50% bond. The system is not perfect, but nobody wants to lose their bond, so in general it works.

**Comment by SmallAndSoft** [comment]
I can see potential for coordinated attack on honest seller by his rivals through proxy buyers. Doing 3x damage is a sure way to put out of business especially when evil actors gang up. Anonymity makes this easier to execute.

So the sellers will be forced to rotate their identities in order to maintain a moving target. This makes building reputation less appealing.
